language: node_js
node_js:
  - "0.10"
  - "0.11"
script:
  - npm run test-travis
after_script:
  - npm install -g coveralls@2
  - cat ./coverage/lcov.info | coveralls
  - npm install -g codeclimate-test-reporter
  - cat ./coverage/lcov.info | codeclimate